### ISSUE TITLE
Jellysac appearing/disappearing

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#1010]
I post here below how looks like a jellysac and what happen after the harvest
1. Jellysac not appearing but shows on action I can do:

![jelly](https://cloud.githubusercontent.com/assets/6795607/15987230/afbb7c52-3021-11e6-8fec-e2c3a4d21fc2.PNG)
1. 

![jelly1](https://cloud.githubusercontent.com/assets/6795607/15987233/ceafb902-3021-11e6-948c-b500a5da7f27.PNG)

3.I harvest

![jelly3](https://cloud.githubusercontent.com/assets/6795607/15987238/e7708ffc-3021-11e6-84c6-87a1f1ecb616.PNG)

4.After the harvest the jellysac appears
![jelly2](https://cloud.githubusercontent.com/assets/6795607/15987245/1252041c-3022-11e6-915f-e79010b4c1b9.PNG)

I hope I was able to explain
they act like pop up appearing and disappearing even without harvest

**Comment by Klikini** [comment]
Most likely related to #1039
