### ISSUE TITLE
Skill Tank is following my avatar

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#1055]
I harvested a tree and after the action the skill tank remains visible and follows the avatar.
Seems like when I had an emblem following my avatar
- I add I just tried to walk for a while along the street and the tank stops following as the avatar reach the street sign.
- I put a screenshot below:

![skill tank](https://cloud.githubusercontent.com/assets/6795607/16198388/141a393c-3706-11e6-8f75-956f24221dbe.PNG)

and skill tank that stop nearby the sign street

![skill tank2](https://cloud.githubusercontent.com/assets/6795607/16198985/37f1b432-3708-11e6-9b51-b5a1347dafe0.PNG)

**Comment by babi1** [comment]
I add that after reboot the tank is gone 
Hope could help to understand what happened

**Comment by Klikini** [comment]
This is very strange, because the positioning code only runs once, so it should never move with you.

I thought that maybe I had forgotten to run the code to close it if the action is cancelled, but it closes then as well.

**Comment by babi1** [comment]
Same happened just few minutes ago, I was mining a Beryl Rock and the Skill Tank didn't close after the action. If this could help I was using FF instead of Chrome (which I usually use)
- I add now i refreshed and I am on Chrome and I haven't this issue no more. On FF moreover the animation of action is missing. Example: Mine a rock I don't see the animation of pick, the animation is steady

**Comment by Klikini** [comment]
Alright. If it's just a Firefox issue: #415
