### ISSUE TITLE
The forum Profile pages 

### ISSUE THREAD

**Issue by anne216** [ChildrenOfUr/cou-issues#1058]
I get this error message when I try to go to my profile or anybody's profile that matter Fatal error: Call to undefined function isDev() in /hermes/walnaweb11a/b228/moo.childrenofurcom/wordpress/wp-content/themes/coui-wp/page-profiles.php on line 39

**Comment by Klikini** [comment]
Just fixed it a few minutes ago.

**Comment by anne216** [comment]
Thank you :)
