### ISSUE TITLE
Blog comments not displaying due to script error

### ISSUE THREAD

**Issue by RobertBlackhart** [ChildrenOfUr/cou-issues#106]
Comments aren't displaying on blog posts. Logged in or not the same issue shows:

![forums_bug](https://cloud.githubusercontent.com/assets/5414318/10178816/22d17e74-66d0-11e5-9f18-d102e4b357f3.png)

**Comment by Klikini** [comment]
It seems to be _only_ for the latest post, not any others.

I am now checking the `$post['replies']` value returned by the forums API, and only running the loop if it is not null. That seems to fix it while keeping the other posts working, though I'm not sure why it sometimes returns null (should, at worst, be `[]`)
