### ISSUE TITLE
Create a recipe for a "newbie starter pack" item

### ISSUE THREAD

**Issue by RobertBlackhart** [ChildrenOfUr/cou-issues#1068]
See http://childrenofur.com/forums/thread?id=192 for details. The idea is that this item would be openable and give the player the items listed. But this item would also be stackable so that the giving player can easily store them in their inventory.

We should also create a quest associated with the giving of these items. Perhaps when the player reaches level 11 (prime number) they will be offered the quest. Then they have to make and give 3 of these to players of level 3 or less.

This would require a "Give Item" action on the player entities which we do not have yet.

**Comment by RobertBlackhart** [comment]
I am going to open a new issue for parts 2 and 3. These parts are not necessary for the basic functionality to work.

**Comment by babi1** [comment]
I add some toughts on the thread. Hope these could help :)
