### ISSUE TITLE
Barnacle and Peat bog misplaced at Mucid Memes

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#1073]
Player can't interact as they are too far  and can't be reached
I put screenshot below

Barnacle:
![barnacle misplaced](https://cloud.githubusercontent.com/assets/6795607/16357120/f7600696-3aed-11e6-9034-8d0469b52dc4.PNG)

Peat Bog:

![peat misplaced](https://cloud.githubusercontent.com/assets/6795607/16357121/06f4173c-3aee-11e6-888d-4f39414711d0.PNG)

**Comment by krisalyssa** [comment]
This appears (these appear?) to be fixed.
