### ISSUE TITLE
Constantly reloading

### ISSUE THREAD

**Issue by sugarj** [ChildrenOfUr/cou-issues#1084]
I try loading the game and it gets there and then a message pops up saying my game is outdated and I can't do anything until I hit "OK" and it reloads again. It's an endless cycle! The pop-up also says that if it pops-up after reloading to contact you so here it is. Thanks!

**Comment by Klikini** [comment]
@sugarj: Is this still an issue?

If so, what browser are you using?

**Comment by sugarj** [comment]
No it's good now thanks, just the very first time I tried loading the game.
