### ISSUE TITLE
Tinkering skill not associated with action

### ISSUE THREAD

**Issue by anne216** [ChildrenOfUr/cou-issues#1131]
I've tried using the Tinkertool to mend some things but it won't do it

**Comment by anne216** [comment]
I actually meant to post this from ingame, but forgot lol :)

**Comment by Klikini** [comment]
What do you mean by "won't do it"? At what point does it not work?

**Comment by anne216** [comment]
Because it never cones up as option to mend anything

**Comment by Klikini** [comment]
If you open the tinkertool window (by right clicking on the tool itself)
you should have options to create and repair tools. The repair options use
up your old tool, but offer discounted item costs.

**Comment by anne216** [comment]
Ok I'll try it again, but last time I tried  I never saw an option to repair

**Comment by anne216** [comment]
Nope I only get Tinker option no mend and then the screen to make tools but no fancy pick or pots and pans and stuff :(

**Comment by Klikini** [comment]
Tinker to create a few of those, then you'll get different tinkering skill
levels to make more tools.

**Comment by babi1** [comment]
As Tinkering is a Skill, is it maybe related to which level one player is?
I could see the very first days all the option even to craft some new tools
Now ( that I have used a lot I should say) I only have the chance to mend tools but not to craft new one , On side note I haven't start any Tinkering Skill too yet

**Comment by anne216** [comment]
Ok i'll try that but not even Tinkering comes up as a skill when I make stuff

**Comment by anne216** [comment]
Nope still nothing :( and no skill popped up either

**Comment by Klikini** [comment]
@anne216: May I have your game username to look up your skills data and see what's happening?

**Comment by anne216** [comment]
Sure it's ~Annie~ And I still think my mining is stuck there has been no change at all since I posted it broken last time , but I've been mining like crazy, thanks :)

**Comment by anne216** [comment]
Bump in case you forgot this :)

**Comment by Klikini** [comment]
Here is your current skill data:

```
{
  "arborology": 3552,
  "bubble_tuning": 46,
  "mining": 4922,
  "croppery": 181,
  "animal_kinship": 1029,
  "alchemy": 3
}
```

These numbers are in "points", which are how many times you have done an action that is related to the skill. Each skill level requires an exponentially increasing number of points, so with mining and arborology so high, it might take a while to reach the next level.

Mining actually maxes out at 2,113 points, so you're done with that one.
The next two levels of arborology come at 4116 and 6516 points.

It's strange that tinkering isn't listed. When my new computer fan arrives, I'll see what I can do about that.

**Comment by anne216** [comment]
Thank you so very much :)
