### ISSUE TITLE
Letters floating above head in all Groddle Heights areas

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1163]
In the old game there was (at least) one area underground somewhere in Groddle Heights where a letter would appear floating over your avatar's head.  Now, this happens in every area in GH. Bug or feature?

**Comment by Klikini** [comment]
This is because I wasn't sure which streets had them, and I didn't want to miss any.

**Comment by anne216** [comment]
All the Streets have them atm in Groddle Heights

**Comment by babi1** [comment]
I remember they were at Thornfad Layers in Groddle Heights

**Comment by lizzard** [comment]
It's kind of fun having them on all the streets!
