### ISSUE TITLE
Some links in Global channel have "span" appended to the url

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1164]
A link to this github repo, if pasted into Global channel, shows up in the channel as this link: https://github.com/ChildrenOfUr/cou-issues/issues/1163%3C/span%3E%3C/p%3E  Other links seem to work correctly, ie a link to https://github.com works just fine. But https://github.com/ChildrenOfUr/cou-issues/issues will have an extra span and closing <p> tag added so the links to report or show bugs don't work correctly in the channel.

**Comment by lizzard** [comment]
I think something must be matching "childrenofur" in the url, for the internal game links and it's catching some outside links wrongly.

**Comment by Klikini** [comment]
The code for it doesn't match "childrenofur", so that's weird. https://github.com/ChildrenOfUr/coUclient/blob/dev/lib/src/display/chatmessage.dart#L148
