### ISSUE TITLE
Energy not increasing as character levels

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1182]
My character is level 19 but its maximum energy level hasn't increased for many levels. It seems stuck at 210.

**Comment by Klikini** [comment]
Does refreshing fix it?

**Comment by lizzard** [comment]
Do you mean reloading the page? If so, no. Re-logging in also hasn't changed the maximum energy level.

**Comment by Klikini** [comment]
Have you collected any iMG quoins? Try doing that. You shouldn't have to, but the code looks a bit messy and that might have something to do with it, so I'm curious if it works.

**Comment by lizzard** [comment]
I definitely have (both the i quoins and the "img" ones in the large bubble)

**Comment by Klikini** [comment]
I found the problem. Your level up _has_ to be from iMG you collect from a quoin because of where @RobertMcDermot put the energy tank increase code.

**Comment by anne216** [comment]
And I have leveled up twice since anf not received any increase in my tank and have collected img qouins as well

**Comment by Klikini** [comment]
After the next update, it will fix your energy tank once your iMG increases.

**Comment by anne216** [comment]
Ok thanks :)
