### ISSUE TITLE
Garden gnome object layers all appear in inventory

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1183]
The garden gnome object looks very odd in inventory. I think it is trying to show all the layers of animation at once. Using Firefox beta, not sure of how it looks on other platforms. In this screenshot the gnome is next to the 3D music box. 

![gnome-layers-wrong](https://cloud.githubusercontent.com/assets/227661/16631489/49581b58-4374-11e6-9e74-d1d31485e89d.png)

**Comment by Klikini** [comment]
It's because it's an entity, so it had spritesheets. The image just needs cropping and re-uploading. Will do.

**Comment by lizzard** [comment]
Earthshakers are similarly wonky when in inventory. Want a separate bug for that?

**Comment by lizzard** [comment]
Also, pumpkin pie.  The image looks too big, and is cut in half.
![pumpkin-pie-art-inventory](https://cloud.githubusercontent.com/assets/227661/16643334/76af6788-43c8-11e6-9aa9-65fbecbe5f4f.png)

**Comment by Klikini** [comment]
Just keep adding them here and I'll get to them when my new computer fan comes in the mail tomorrow.
