### ISSUE TITLE
Jal Non-existent map boundary

### ISSUE THREAD

**Issue by Mturtle7** [ChildrenOfUr/cou-issues#1188]
My character seems to be able to swim above the visible mini-map boundary for all the Jal streets.
![screen shot 2016-07-07 at 12 27 50 pm](https://cloud.githubusercontent.com/assets/20344551/16667086/851905fa-443f-11e6-8acb-947e7a59c6f7.png)

**Comment by lizzard** [comment]
Duplicate of issue 1187
