### ISSUE TITLE
Skills not advancing to the next level

### ISSUE THREAD

**Issue by cthulhu3** [ChildrenOfUr/cou-issues#1317]
Despite hundreds/thousands of actions, the Arborology and Mining skills do not advance to level 2 or 3.

**Comment by babi1** [comment]
I have any problem instead with Arborology ( I can see the progress of my skill increasing) while I have just noticed that Mining even if mine is stucked at the begin of lvl 2 the quanity of gem per each sparkly rock is uber over the average  of Mining 2 and each rock give a lot of more of what  we were used to have just a month ago, morover depends on where one player goes to mine too. I haven't checked yet all classic mining streets but I can say for sure Pollokoo Region is one of them together with Ilmenskie Deeps
I suppose is a bug : )

**Comment by Klikini** [comment]
Skills are wonky due to the server being slow to respond and sometimes dropping the pending number increases, so they don't get counted. We're currently trying to figure out how to reduce this.
