### ISSUE TITLE
[Mining] Rocks don't wear down

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1406]
All these happened in various rooms in Callopee. None of them happened prior to 1.4.4 release.
1. Rocks don't wear down when mined. I can mine one rock forever.
~~2. Sometimes the chunks that appear are the wrong mineral - i.e. mining dullite but chunks of sparkly are added to my inventory~~
~~3. Sometimes no energy is deducted for mining, sometimes no chunks appear in inventory.~~
~~4. Sometimes I have to hit Enter several times for mining to begin.~~
~~5. Sometimes the 1. Mine selection box stays on while and after the mining action happens.~~
~~6. Sometimes the mining action happens without the 1. Mine selection box ever having appeared.~~

**Comment by hawkwell** [comment]
The problems I listed in my original report of 4 hours ago appear to have all disappeared. Mining now functions normally. Before the 1.4.4 update I was at mining skill level 1. I am now at level 3 and each mining operation, which formerly used 10 energy units, now uses only 2. I am guessing this is a result of the update correcting earlier problems, but I really have no idea.

**Comment by hawkwell** [comment]
Spoke too soon. I am now still getting instances of the 1. Mine dialog not appearing or not disappearing appropriately. More seriously, rocks are being half consumed by mining and then further mining operations yield no chunks and cost no energy and I get the message there's not much left to mine while half the rock is still there. I had this happen with one rock of sparkly the very first time I mined it.

**Comment by Klikini** [comment]
Reopened as requested in #1409

**Comment by hawkwell** [comment]
I'm currently finding that mining is fine for a good while and then all the bugs start happening. Reloading fixes it so the bugs disappear.

**Comment by Klikini** [comment]
@hawkwell: Is this still an issue?

**Comment by hawkwell** [comment]
There are still occasional mining issues, though they are cleared up with a reload. It has been suggested elsewhere that hitting Enter too often or too fast can cause these problems. This seems to me, at least sometimes, to be the case. In any event other than occasionally having to reload the page I am not currently seeing problems with mining. A problem that occurs infrequently and is cleared up with a reload hardly seems worth spending time on. Fine with me if this is closed.

**Comment by Klikini** [comment]
That's #1451
