### ISSUE TITLE
New global chat bugs

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1407]
These new since 1.4.4 release.
1. Global chat regularly spools a new "Players in This Channel" list - it seems to be once every minute of in-game time. The people listed appears to be a changing subset of those actually in game.
2. My attempts to post to Global Chat have erratic success. Sometime the post appears in the chat window - sometimes it doesn't.

**Comment by hawkwell** [comment]
Global chat now appears to be functioning normally.

**Comment by Klikini** [comment]
The "Players in this channel" prints every time the server restarts. This restarting would also break message sending.

It was restarting because a number in someone's steps taken stat got too big to store.
