### ISSUE TITLE
Tree awards don't get back-awarded

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1466]
Since tree petting and watering achievements were fixed, players get only the highest appropriate achievement for an action they're doing. For example, if you had petted 40 bean trees and then pet a 41st, you get the 41 trees petted award.  But you will never get the 11 trees petted award.  This is because the code checks the highest achievement first and if you have accrued that many actions in a category, it stops checking.  We could backfill this once for current players, ignore it since new players may never see the issue, or fix it some other clever way.  

It will come up again though since not all achievements are enabled.

**Comment by Klikini** [comment]
Would it be awful to just wait until The Great Reset, so everyone could get them in order again?

**Comment by lizzard** [comment]
No it wouldn't :)

**Comment by anne216** [comment]
Yes I agree, i got all the higher one's for petting but none of the lower ones, not sure about watering, as it's been raining verytime I log in lately lol :)
