### ISSUE TITLE
Firefly jar art missing on dev server

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1551]
I can see a slot for the firefly jar at the Tool Vendor (on the dev server)  but the art is missing. Noting in case Elle wants to supply it...

**Comment by ElleLament** [comment]
<img width="590" alt="screen shot 2016-08-27 at 11 13 25 pm" src="https://cloud.githubusercontent.com/assets/20787290/18031982/ee0732d2-6cab-11e6-89ad-4e5b51cda242.png">

BAM!!!!!!!!!!! AND it's an SVG! So pretty! <3 <3 <3
