### ISSUE TITLE
CofU user profile data not loading

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1557]
Profile pages for CofU users are displayed but are not filled with data. The current street graphic and avatar do not load. Stats and Favor are all zeros, but awarded achievements are shown.

**Comment by Klikini** [comment]
Could you please check the console for errors?

Ctrl + Shift + I, Console tab

**Comment by Klikini** [comment]
Nevermind, it was something I broke.

**Comment by Klikini** [comment]
Fixed.

**Comment by hawkwell** [comment]
Nice to see it working again. Thanks.
