### ISSUE TITLE
Stafli Joli Visiting Stone broken (goes nowhere)

### ISSUE THREAD

**Issue by heidipollock** [ChildrenOfUr/cou-issues#1573]
Clicking the Visiting Stone on Stafli Joli street takes you to the loading screen (just a big green blank). Reloading browser window returns you to the street in front of the stone.

Attaching a picture even though it's pretty pointless.

![image](https://cloud.githubusercontent.com/assets/10406735/18108744/80dce300-6ec2-11e6-9975-0af08a9e1dd3.png)

**Comment by Klikini** [comment]
Fixed in dev
