### ISSUE TITLE
Pallur Runnar Street should be marked broken

### ISSUE THREAD

**Issue by heidipollock** [ChildrenOfUr/cou-issues#1574]
If you head right from the Stenina Jora/Snullin Ballin sign you drop down below the street. Walking right or left eventually seems to place you back topside but it's disconcerting and potentially a trap.

![image](https://cloud.githubusercontent.com/assets/10406735/18108779/ba8e8bb2-6ec2-11e6-9124-5c66a04f5b9b.png)

**Comment by Klikini** [comment]
#1399
