### ISSUE TITLE
Moving item from one bag slot to no bag slot leaves item icon hovering in place

### ISSUE THREAD

**Issue by heidipollock** [ChildrenOfUr/cou-issues#1576]
Relogging clears the icon but reloading (I think, can't fully remember) does not. See music block icon in attached image.

![image](https://cloud.githubusercontent.com/assets/10406735/18108878/551b8dce-6ec3-11e6-82ef-f5607a0acff1.png)

**Comment by krisalyssa** [comment]
This appears to be fixed.
