### ISSUE TITLE
Can water tree during rain on Oktyabrya

### ISSUE THREAD

**Issue by heidipollock** [ChildrenOfUr/cou-issues#1581]
![image](https://cloud.githubusercontent.com/assets/10406735/18143783/5c106d24-6f78-11e6-9016-ee12b003e4f0.png)

**Comment by heidipollock** [comment]
Same problem on Clamber Crag.

Is it useful to lump a similar interaction problem on a different street together or would you prefer separate bug entries?

![image](https://cloud.githubusercontent.com/assets/10406735/18225311/08d50b04-71a5-11e6-9a96-37d9825d6349.png)

**Comment by Klikini** [comment]
Most interaction problems aren't street-specific, so all together is best.
