### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1588]
Having left myself logged into the game, I came back to that tab in my Chrome browser a couple of hours later and found it was displaying the login window. I entered my email and password but was not logged in. Instead the words: **_Instance of 'Progress Event'_** were displayed in red letters immediately below the password field in the login window. I closed the tab, cleared my browser cache, closed and restarted the browser, all to no effect. I still get the same message when I attempt to log in.

**Comment by hawkwell** [comment]
I find I get the same **_Instance of 'Progress Event'_** response regardless of what I put in the email and password fields or even if I leave them both blank.

**Comment by hawkwell** [comment]
Login with gitHub got me past the login screen but still endlessly "chatting with server" never preparing world.

**Comment by babi1** [comment]
yep same here
tried GitHub, Fb Google 
all same I keep chatting with the server

**Comment by hawkwell** [comment]
I can now log in both by email/pswd and through Git/Hub. Problem apparently fixed or went away of its own accord.

**Comment by babi1** [comment]
me too i get in without problem 
issue closed I suppose....

**Comment by SmiVan** [comment]
I'm experiencing the same issue with the red `Instance of 'ProgressEvent'` message whenever I try to log in through email/password and I get stuck on "Good to see you" with "Chatting with server..." if I use the google identification. 

Tested on Mac OS 10.8.5, Chrome 49.0 and Firefox 48.0.2, to no avail.

Using the firefox dev tools reveals the following errors:
`Error loading server data: Instance of 'ProgressEvent' 0:00:00        index.html.polymer.bootstrap.dart.js:42837:70`

`Error initializing interface: NullError: J.F(...) is null 0:00:00        index.html.polymer.bootstrap.dart.js:42837:70`

```
Error: 
dart<.e()
        index.html.polymer.bootstrap.dart.js:1973
dart<.bdl.$0<()
        index.html.polymer.bootstrap.dart.js:21530
dart<.bd8<()
        index.html.polymer.bootstrap.dart.js:18408
dart<.c1D<()
        index.html.polymer.bootstrap.dart.js:18410
dart<.b8A.$1<()
        index.html.polymer.bootstrap.dart.js:18560
dart<.bh9.$0<()
        index.html.polymer.bootstrap.dart.js:2693
dart<.IJ.xX()
        index.html.polymer.bootstrap.dart.js:1310
dart<.Bc()
        index.html.polymer.bootstrap.dart.js:1058
dart<.bh7<()
        index.html.polymer.bootstrap.dart.js:2034
dart<.ai/z</<()
        index.html.polymer.bootstrap.dart.js:2042
n()
        webcomponents.min.js:11
t()
        webcomponents.min.js:11
```

I hope this helps.
