### ISSUE TITLE
weather reports for other regions

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1618]
Since you've introduced weather to Ur it would be really nice to be able to check out the weather in different regions before setting out to travel. (Just like IRL!) Maybe I'm thinking about a major tree harvesting expedition and would like to go where it's raining. Or maybe I'm just going wandering but want to go somewhere with sunny weather.

**Comment by Klikini** [comment]
Note to future self:

For this, I'm thinking about a button in the map window that shows up when viewing a hub, and clicking it opens the weather window with a specified hub (rather than the current one).

**Comment by Klikini** [comment]
https://github.com/ChildrenOfUr/coUserver/commit/c19061a0890e2868f8f25647e633b9532a55dc3e

**Comment by Klikini** [comment]
@hawkwell: After the next release, clicking the weather icon while viewing another region in the map will show weather for that region instead of your current location.

**Comment by hawkwell** [comment]
@Klikini: Sounds great! Thanks!
