### ISSUE TITLE
NPC interactions in Local Chat are noisy

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/cou-issues#1634]
We just added rock, animal and I think tree interactions in Local Chat. You see everyone's interactions and the entity speech in chat. That is kind of realistic (we all "hear" whatever is said on the street) and yet it is very noisy if there are many players on a street doing things. It means that we have some trouble seeing each other's actual chatting on a busy street, in a mining party, and so on. 

Suggestion, what if we see only the result of our own interactions, like we do when feeding a baby animal?  In that case, the animal is talking in local chat, but in a smaller font, slightly greyed out, and only visible to the person doing the interacting. We could get more player feedback and see what people think here.

**Comment by Klikini** [comment]
There's currently no way for the client to tell if the message is from your action or someone else's, so the server would need to send that info.
