### ISSUE TITLE
Runaway Cubimal!

### ISSUE THREAD

**Issue by SingingHead** [ChildrenOfUr/cou-issues#1644]
Good news: the cubimals now appear when racing them!! However, when racing one it stopped and appeared to be running in place. When I selected it to pick it up, the cubimal remained in place so I tried picking it up several times. When I opened my bags, several of the cubimal appeared inside for each time I tried to pick it up.

**Comment by Klikini** [comment]
I need to disable the pickup action then...there shouldn't be a way to duplicate them!
