### ISSUE TITLE
Encyclopedia Won't Load

### ISSUE THREAD

**Issue by SingingHead** [ChildrenOfUr/cou-issues#1675]
For the past 3 days, the Encyclopedia won't load for me. I'm not a coder so I don't know if the info I'm about to provide will be helpful at all. It comes from the Developer Tools console; I'm using Chrome. The first is a warning, the last two are errors:
- SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
- Failed to load resource: http://childrenofur.com/encyclopedia/dart/main.dart
  the server responded with a status of 404 (Not Found)
- Uncaught [main.dart.js:782](http://childrenofur.com/encyclopedia/dart/main.dart.js)

I'm unable to copy the html code but I typed out this line since it includes "error":

``` html
<div class="modal fade in" id="load-error" aria-hidden="false" style="display: block;">...</div>
```

Thanks so much for looking into this! I appreciate it. If you need more info, please let me know!

**Comment by SingingHead** [comment]
It seems the line of code I typed isn't appearing; not sure why.

**Comment by Klikini** [comment]
It was because it tried to render the HTML instead of showing the code.

As far as the encyclopedia, I just pushed an update that should fix it soon.
