### ISSUE TITLE
Partial login issue

### ISSUE THREAD

**Issue by TransplantedEntwife** [ChildrenOfUr/cou-issues#172]
I am trying to log in and I'm as far as the last location loading. However, my avatar is not appearing and the music is still the login music. In addition, none of my stats/currants/items are showing (nor is my Glitchen avatar). I've done a complete reboot of my laptop and the issue persists (I tried to send an in-game bug report without any success). 
![screenshot 2015-10-23 18 17 08](https://cloud.githubusercontent.com/assets/6945127/10706996/5de8dd78-79b2-11e5-8698-95808bdc3a25.png)

**Comment by Klikini** [comment]
It looks like the server crashed. I fixed the bug that caused the crash (https://github.com/ChildrenOfUr/coUserver/commit/c742de3c7bafae4cc1b5981537dac16f2ce66eb2) and restarted, so you should be good to go now, @TransplantedEntwife :smile:!
