### ISSUE TITLE
Mail inbox doesn't scroll

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1744]
I'm using mail to store stuff. Once the inbox window fills up, there is no way I can find to access new mail. I can just see the tip of the next message at the bottom of the inbox, but I have to delete something in order to access it.

**Comment by dazulu** [comment]
I'll take a look. Hopefully just a CSS tweak

**Comment by dazulu** [comment]
Fixed for next release!
