### ISSUE TITLE
Zilloween Recipes

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#1778]
Awesome pot->   Hi- Sucrose Corn Syrup Square -> 1 Tiny bubble, 1 Corn, 1 Honey, 1 Roasted Pepitas
Knife & Board ->  Raw Bio Organic Carobish Treat -> 1 Clump of Jellysac , 1 Guano, 1 Roasted Pepitas

**Guano** could be a problem, I tried to feed batterfly in order to get guano but I didn't get any I  suppose isn't implemented yet

**Comment by ElleLament** [comment]
@lizzard Is guano fixed now?

**Comment by babi1** [comment]
I just tried now to feed some batterflies but again no guano and the food isn't taken from my bags

**Comment by RobertBlackhart** [comment]
I just checked. Yes guano appears to be working as intended in the latest dev server.

This should be the commit that fixed it: https://github.com/ChildrenOfUr/coUserver/commit/c980460a182b7428ee62479d5856d3b93f3f3cc0#diff-93c17d343309786d56b10fc2380b960a

**Comment by lizzard** [comment]
Yup, it should be fixed in dev, it was this issue: https://github.com/ChildrenOfUr/cou-issues/issues/1559
