### ISSUE TITLE
Warn players of teleport cost

### ISSUE THREAD

**Issue by RobertBlackhart** [ChildrenOfUr/cou-issues#1902]
In the mini-map, when you click on a street, you are presented with two options: teleport and navigate. We should make it clear that teleporting costs X energy and navigating is free.

**Comment by SingingHead** [comment]
There is a warning, in fact. When you mouse over the word, "Teleport", a speech bubble appears stating "Spend 50 energy to get here right now." When you mouse over "Navigate" a speech bubble states "Get Walking Directions."

**Comment by RobertBlackhart** [comment]
You're right. I'm so used to using the hot keys that I forgot that was even there. I'll close this.
