### ISSUE TITLE
Stuck on street in Salatu

### ISSUE THREAD

**Issue by CoolNinja2** [ChildrenOfUr/cou-issues#2007]
Towards the right of the map of Salatu, a road is unlabeled. I tried to teleport to this street, but then got stuck on the street loading screen. After logging out, the game now refuses to load and gets stuck on "Preparing world..." I just started playing, so would like to continue, but this means I can't. Help getting out would be appreciated of course, if the street cannot be fixed soon, but I fear others may make the same mistake as me. My username is CoolNinga2 (no, not a typo).

EDIT: After further digging, I found that it was Salatu Start, and many are currently in the same situation:
http://childrenofur.com/forums/thread?id=259

**Comment by Klikini** [comment]
I just pushed an update that should fix this for everyone, but I also teleported you to Cebarkul just in case.
