### ISSUE TITLE
Inability to log in

### ISSUE THREAD

**Issue by steelwolf** [ChildrenOfUr/cou-issues#2041]
I am using Chrome Version 54.0.2840.71 (64-bit) on macOS Sierra 10.12.1. 

I made an account in 2015 but I've not been able to successfully log in. Entering an email and password on the log in page produces an error message:
`Instance of 'aF'`

There is no way to progress beyond this message.

**Comment by Klikini** [comment]
1. What is the email you are entering? (Just the part before the `@` for privacy)
2. What is the username of the account you're trying to log in with?

**Comment by steelwolf** [comment]
Thank you for the response! 

I tried to log in again from a different connection and things seemed to work. May have just been that location.
