### ISSUE TITLE
can't get past loading screen 

### ISSUE THREAD

**Issue by htebazile** [ChildrenOfUr/cou-issues#2056]
my account is not working and hasn't been for a little over 2 weeks.

it goes to loading screen and won't go past. i did log out then logged back in, but that doesn't make a difference.

i'm not sure if it is due to teleporting to a broken street or if it's something else.

thanks in advance for fixing my account, i look forward to playing again!

i hope you all have a great thanksgiving holiday!

- htebazile

**Comment by Klikini** [comment]
I have teleported you to Cebarkul, please try again and let me know if it works.

**Comment by htebazile** [comment]
THANK YOU Klikini!!!!! i'm back in the game!

really appreciate your help.

**Comment by Klikini** [comment]
YAY!

You're welcome!
