### ISSUE TITLE
accidentally teleported somewhere that may not exist

### ISSUE THREAD

**Issue by tanithlow42** [ChildrenOfUr/cou-issues#2075]
I teleported somewhere in Bortola and now the game won't load. I once had a visiting stone try to send me to Old Groddle and that wouldn't load either but it fixed (and sent me back to where I was before) when I refreshed the page. This time, the loading screen gets stuck on "Preparing world," and my profile shows me as "Last seen in Bortola Start." ETA: Username is TanithLow

**Comment by Klikini** [comment]
@tanithlow42 I have teleported you to Cebarkul
