### ISSUE TITLE
Visting stone

### ISSUE THREAD

**Issue by VivaGloria** [ChildrenOfUr/cou-issues#2104]
![cou02](https://cloud.githubusercontent.com/assets/25110112/21957901/333d46ba-da99-11e6-818b-fa4178c33e2c.png)
Typo on visiting stone dialogue -- it says Visting ...
tried submitting this via bug reporter in game but I must have closed it too soon

**Comment by Klikini** [comment]
This has been misspelled for months and nobody has noticed. Good eye!
