### ISSUE TITLE
Can't start playing

### ISSUE THREAD

**Issue by dixonkme** [ChildrenOfUr/cou-issues#2120]
Stuck at the globe screen with the music going. I've used the username I had on old Glitch, my avatar's come up and I've clicked 'That's totally me'. Then, nothing. Just hangin' around hoping to start playing! Hope you can help. Thanks.

**Comment by dixonkme** [comment]
Now it says 'Greetings [my old Glitch name] but still says hey, a new face below and I've gone through the entering my old Glitch name again and saying 'That's totally me' to the avatar but still stuck with the globe spinning.

**Comment by Klikini** [comment]
Can I please get your username so I can look it up in our database?

**Comment by dixonkme** [comment]
Hi, I was Molly Bloom on the original Glitch, so that's what I've been
using again on Children of Ur. Thanks :)

**Comment by Klikini** [comment]
Your account was created before we implemented our new login system, so could you please try creating a new one? I renamed `Molly Bloom` to `Molly Bloom 2` so you can reuse the name.
