### ISSUE TITLE
Teleport to nonexistent street, now can't reach world

### ISSUE THREAD

**Issue by hattieshoe** [ChildrenOfUr/cou-issues#2147]
In the Bortola map I saw a street with no name and (foolish experiment, I know) decided to try teleporting to it. A page came up with the title "Bortola Start" but the loading bar stayed at 0%. After a while with nothing happening, I reloaded the page, but now the main loading page stays at "preparing world" and never gets past that for me. What can I do? Thanks!

**Comment by hattieshoe** [comment]
I can't log in to the forums page now either. It accepts my login information but keeps reloading the welcome screen.

**Comment by Klikini** [comment]
What is your Children of Ur username? I can teleport you out.

**Comment by hattieshoe** [comment]
It's hattieshoe. Thank you!

**Comment by Klikini** [comment]
​Alright, you should be in Cebarkul next time you log in.

**Comment by Klikini** [comment]
Alright, you should be in Cebarkul next time you log in.

**Comment by hattieshoe** [comment]
Unfortunately, it still sits there on the entry screen where it says
"Preparing world" and won't take me to the game. (Although now I can log in
to the main site where the forums are.)

**Comment by Klikini** [comment]
Which browser are you using? Can you try hitting Ctrl + F5 after the page loads and see if it helps?

**Comment by hattieshoe** [comment]
Thanks, it is letting me in now. I appreciate your help!
