### ISSUE TITLE
Mixed Content Http/Https childrenofur.com

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#2349]
Just had the warning and opened in console:
I am running on Chromium 58.0.3029.81 

jquery.min.js:4 Mixed Content: The page at 'https://childrenofur.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://server.childrenofur.com:8181/getGameStats'. This request has been blocked; the content must be served over HTTPS.

**Comment by Klikini** [comment]
Oops, just saw this issue. However, I fixed it a while ago :)
