### ISSUE TITLE
Can't even log in?

### ISSUE THREAD

**Issue by Acronymph** [ChildrenOfUr/cou-issues#2623]
Get the error message "Syntax The URI is malformed" which is not even English, IMO.  Oddly, if I click the GitHub logo from that login screen after failure, the page does display an Ur bubble and "Good to see you" but nothing else happens.

This has been going on a couple weeks.  Thought it was me at first, figured finally to bring it to your attention.

~drops cubi in shrine~

**Comment by stream27** [comment]
Having a similar problem. I don't get a syntax error, but get stuck on this screen

![Capture](https://user-images.githubusercontent.com/48421223/54093560-69fb0480-436f-11e9-9ece-a65111803d3d.JPG)

**Comment by mya-21** [comment]
I'm also experiencing the same issue as @stream27, and am getting stuck on the loading screen

**Comment by Klikini** [comment]
@Acronymph @stream27 The last game update was March 23rd. Could you both please try again with the latest version?

**Comment by Klikini** [comment]
Also, let's combine this with #2715
