### ISSUE TITLE
alakol start, stuck (edit: fixed!)

### ISSUE THREAD

**Issue by ashfie1d** [ChildrenOfUr/cou-issues#2650]
teleported to one of the alakol start maps, it wouldn't load a map and upon refreshing, won't go past the "loading, preparing world" screen. a TP out would be great, username is "Noctuakul"

edit: sent an email and was TPed out. thanks again!

**Comment by yalla** [comment]
Cross-reference: https://gitlab.com/ChildrenOfUr/coUserver/issues/4
