### ISSUE TITLE
My game is outdated!? 

### ISSUE THREAD

**Issue by sorjjjjjie** [ChildrenOfUr/cou-issues#2706]
Yesterday, while in the game, we were advised of a sort of update about to take place. I was booted out as expected and then received this message: Your Game is outdated. Click OK and we'll try to fix that for you so you can play. If you see this message after reloading, please contact Children of Ur for help.
"Help!"

When I log back in, I have zero energy, my avatar is mia, and stash in front is empty. I get the same pop-up message about my game being out dated and cannot do anything. Please help!

from Teet
03/24/2019

**Comment by Klikini** [comment]
Sorry, I'm just now seeing this. Could you try again and let me know if it's still broken?

**Comment by sorjjjjjie** [comment]
Hi Andy,

It's still broke. I first see a web page about which browsers work for the
game (I use Chrome) the the word spins and music plays but I never make it
in.

Thanks!

Patty aka Teet

**Comment by Klikini** [comment]
But the message about the game being outdated is no longer showing up,
correct?

Several other people are having this issue so I'm trying to solve it for
everyone :)

**Comment by sorjjjjjie** [comment]
Correct, no longer seeing Msg about the game being outdated. It appears the welcome screen has changed to "Nice of you to join us teet" , though I still cannot get in.

**Comment by Klikini** [comment]
Okay, then I think this is the same problem as #2715
