### ISSUE TITLE
Cannot get back in the game

### ISSUE THREAD

**Issue by sorjjjjjie** [ChildrenOfUr/cou-issues#2713]
First I had a popup while in the game on 3/23/19 that stated: childrenof ur.com say your game is outdated. Click OK and we'll try to fix that for you so you can play. If you see this message after reloading, (I did) Please contact Children of Ur for help. 

I also got this page:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at cgiadmin@yourhostingaccount.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Klikini** [comment]
That error should be fixed now, please try again :)
