### ISSUE TITLE
Can't log into game

### ISSUE THREAD

**Issue by Diva101** [ChildrenOfUr/cou-issues#286]
I keep trying to log into the game and it loads then gives me 1 of 2 error messages - either says the server is down, or says Wait you were just about to win - then reloads and tries to log me in again. It does this over and over in a loop for as long as I sit there and let it. I signed up 2 days ago and have yet to be able to play this game. 

If the server is actually down then it's been down for a long time. Otherwise there is another issue with my login going on here.

**Comment by Klikini** [comment]
The server has been crashing quite frequently the last few days (see http://status.childrenofur.com). Can you please test it now, while the server is up, @Diva101?

**Comment by Diva101** [comment]
Have tried off and on all day.... still have not been able to play. 

-----Original Message-----

**Comment by Klikini** [comment]
Is this still an issue?

**Comment by Diva101** [comment]
Yep. Have not been able to log in yet. I have given up on ever playing this game, unless you have a solution to fix it. 

-----Original Message-----

**Comment by Klikini** [comment]
Which browser are you using, and have you tried using incognito/private mode?

**Comment by Diva101** [comment]
I am using Firefox, the latest version.... I have also tried using Google Chrome and I get the same result there. 

How do I use incognito/private mode?

-----Original Message-----

**Comment by Klikini** [comment]
In Chrome (our suggested browser) it's Ctrl + Shift + N, I'm not sure about Firefox.

**Comment by Klikini** [comment]
Did you get it working?
