### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Klikini** [ChildrenOfUr/cou-issues#386]
- [x] Data
- [x] Database support
- [x] Server support
- [x] Client UI

**Comment by RobertBlackhart** [comment]
Does the 'Data' item refer to the json files needed to describe the quests?

**Comment by Klikini** [comment]
@RobertMcDermot Yes.

**Comment by RobertBlackhart** [comment]
@Klikini I'm sure you saw. I could use your help making the quest log ui more good.
