### ISSUE TITLE
Entities can be clicked on through windows

### ISSUE THREAD

**Issue by Klikini** [ChildrenOfUr/cou-issues#400]

**Comment by RobertBlackhart** [comment]
Does this mean right-click? If so, this has been true forever and is due to how the click thing works. Would be easy to do an !ignoreKeys on it.

**Comment by Klikini** [comment]
That was my first though, but it didn't work (at least I thought I had put it in the right listener)

**Comment by ppvk** [comment]
Still happens sometimes.
