### ISSUE TITLE
Map search sucks

### ISSUE THREAD

**Issue by Klikini** [ChildrenOfUr/cou-issues#401]
![image](https://cloud.githubusercontent.com/assets/1693960/12498390/ce941dac-c067-11e5-968d-57527f2a4800.png)

**Comment by RobertBlackhart** [comment]
![map_search](https://cloud.githubusercontent.com/assets/5414318/12531689/1649454c-c1cf-11e5-9282-7442f698c85e.png)

Calculate the partial matches and save to a list
Use Levenshtein Distance to sort the list
Add the sorted list to the ui
