### ISSUE TITLE
This is How Looks MuufoStart

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#550]
I was wandering with the end street stones and I landed at Muufo Start
This is like it looks to me:

![muufo start](https://cloud.githubusercontent.com/assets/6795607/13735861/d4e4b822-e9ae-11e5-977b-024bb88a32f5.JPG)

**Comment by ElleLament** [comment]
@Klikini Can't pull street up on map or in Glitch's Encyclopedia. Possible test street?

**Comment by Klikini** [comment]
All (hub name) Start streets should be hidden, and are in dev. Soon to go live.

**Comment by Acronymph** [comment]
Street isn't yet named, but path is visible.  Attempted to teleport to Muufo Start from another street within Muufo.  Got stuck at transition and street never loaded.  Attempted reload twice.  Can't get back in world at all now... apparently doomed to chat with server forevermore!

**Comment by Klikini** [comment]
@Acronymph What's your in-game username? Close the game and I can teleport you to Cebarkul.

Once we get the next release out, this will be fixed!

**Comment by Acronymph** [comment]
Acronymph is my username as well.  Thanks!

**Comment by Klikini** [comment]
@Acronymph Teleported!

**Comment by Acronymph** [comment]
Devs rock... so much.  <3
