### ISSUE TITLE
Rook's Way 1 Visiting Stone

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#553]
Some Visiting Stones dont work
Here what I have at Rook 's Way 1
p.s. : Same thing has happened before with other Visiting Stones, To go back to normal status I have to refresh and bring me back to the original dead end street

![endstreet](https://cloud.githubusercontent.com/assets/6795607/13776327/c105ac8e-eaa9-11e5-9388-831274d27776.JPG)

**Comment by Klikini** [comment]
Fixed by limiting search to visible streets
