### ISSUE TITLE
Hakusan Heaps Towers / Sabudana Drama Towers how they look

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#554]
I landed here and this is how it looks:

![hakusan](https://cloud.githubusercontent.com/assets/6795607/13776693/cf36ca02-eaab-11e5-9b00-d4b51f05533c.JPG)

**Comment by babi1** [comment]
and here:

![sabudana](https://cloud.githubusercontent.com/assets/6795607/13777154/89af53b6-eaae-11e5-98db-f2a8dedd70ff.JPG)

**Comment by Klikini** [comment]
I'm surprised you could load those streets at all! Most hidden/indoor/instanced/special locations are missing.

**Comment by babi1** [comment]
I just visit the dead end streets, sometimes they brought me in these locations sometimes in other "normal" streets in other regions.

**Comment by Klikini** [comment]
I have fixed it (in dev, it will be public with the next release) so that the visiting stones will not take you to streets that aren't listed on the map.
