### ISSUE TITLE
Items get stuck during dragging

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#563]
I tried again to move items on my bags and I tried to drop an Emblem of Sprigan 
Thats what happened and it keeps following my avatar everywhere  : D
![jumpingem](https://cloud.githubusercontent.com/assets/6795607/13827032/ceb1b8e8-ebba-11e5-8912-b8190c509349.PNG)

**Comment by babi1** [comment]
Issued solved refreshing but can be done again if I try to move some items in the bags. They seem to overlay in the slot, already full with another item,  and dont drop but follow the avatar.

**Comment by Klikini** [comment]
No matter how much I walk and drag things around, I can't make this happen. Maybe something got fixed in the dev branch that isn't live yet?

I'm closing this for now, but feel free to re-report after the next update if it happens again.
