### ISSUE TITLE
Corrupted Inventory

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#569]
My Inventory is corrupted again
I have the same issues as before
I would prefer if it isnt a problem for you, to have a reset, I am sorry to bother so much but I have all the same issue I had before. The reset made Klikini worked perfectly and if it is possible I would like to keep my inventory proper and even with less item I suppose is the best at the moment.
Thanks a lot and sorry for all the trouble

**Comment by Klikini** [comment]
I've reset it again and given the currants back.

**Comment by babi1** [comment]
Thanks a lot! At the moment all seem working properly again! I am so happy thank you very much. I still have the 2 new Quests opened but maybe is better I will wait  a little before trying to complete them. Now I try the basic interactions and if all will be good I will try then to complete the Quests.
Again thanks a lot for your time and help.

**Comment by Klikini** [comment]
No problem :smile:
