### ISSUE TITLE
Emblem out of bag following avatar

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#596]
Again I was moving items in my bags and I have an emblem out of bag (notice I cant drop any item at the moment) following the avatar
![fyingemb](https://cloud.githubusercontent.com/assets/6795607/13914962/0cfcec68-ef52-11e5-8c53-68c2fc270a1f.PNG)

**Comment by Klikini** [comment]
The inventory has been tweaked a bit in the upcoming update, please report this if it happens again after we release that.
