### ISSUE TITLE
Username undefined, and Glitchen sprite import bug

### ISSUE THREAD

**Issue by SmiVan** [ChildrenOfUr/cou-issues#620]
Greetings CoU developers.

I have encountered a bizzare bug relating to my account.

I used to play CoU a while back (over 6 months ago), and back then I have registered and used the set command to set my username as SmiVan (which is my [old glitch username](https://www.glitchthegame.com/profiles/PUVHR4F9A8A3C09/)).

Returning to the game just recently today, I found that I cannot login with my email and I had to register it again. Upon registering and logging in, it put me straight into the game, skipping the "What do you want to be called?" step. I found that I have my old username "SmiVan" set to me even though I have not entered it again. However, the sprite that I had was still of the cupcake glitchen character, and my sprite was missing from my [profile page](http://childrenofur.com/profile/?username=SmiVan). 

I have been advised by babi to use a different email and register again. 
Upon doing so, I have found that when I typed in my username on the "What do you want to be called?" step, the username box gets automatically deselected when I press the letter m on the keyboard. The console prints out the following error message:

> Uncaught TypeError: Cannot read property 'gfb' of null
> dart.M1.b4S @ index.html.polymer.bootstrap.dart.js:9573
> (anonymous function) @ VM23862:2
> dart.aRm.$1 @ index.html.polymer.bootstrap.dart.js:6030
> dart.bcY.$0 @ index.html.polymer.bootstrap.dart.js:2673
> dart.HA.xw @ index.html.polymer.bootstrap.dart.js:1300
> dart.zQ @ index.html.polymer.bootstrap.dart.js:1048
> dart.bcW @ index.html.polymer.bootstrap.dart.js:2026
> (anonymous function) @ index.html.polymer.bootstrap.dart.js:2034

on typing i it gives out the following console error: 

> Uncaught dart.f @ index.html.polymer.bootstrap.dart.js:1965
> dart.b9g.$0 @ index.html.polymer.bootstrap.dart.js:20363
> dart.b94 @ index.html.polymer.bootstrap.dart.js:17234
> dart.bW0 @ index.html.polymer.bootstrap.dart.js:17236
> dart.b4k.$1 @ index.html.polymer.bootstrap.dart.js:17386
> dart.bcY.$0 @ index.html.polymer.bootstrap.dart.js:2673
> dart.HA.xw @ index.html.polymer.bootstrap.dart.js:1300
> dart.zQ @ index.html.polymer.bootstrap.dart.js:1048
> dart.bcW @ index.html.polymer.bootstrap.dart.js:2026
> (anonymous function) @ index.html.polymer.bootstrap.dart.js:2034`

and on pressing enter it gives the following error:

> Uncaught TypeError: Cannot read property 'giz' of null
> (anonymous function) @ index.html.polymer.bootstrap.dart.js:12748
> dart.L_.abU @ index.html.polymer.bootstrap.dart.js:12751
> dart.aRH.$1 @ index.html.polymer.bootstrap.dart.js:12999
> dart.bcY.$0 @ index.html.polymer.bootstrap.dart.js:2673
> dart.HA.xw @ index.html.polymer.bootstrap.dart.js:1300
> dart.zQ @ index.html.polymer.bootstrap.dart.js:1048
> dart.bcW @ index.html.polymer.bootstrap.dart.js:2026
> (anonymous function) @ index.html.polymer.bootstrap.dart.js:2034

The "That's totally me" button is then grayed out, and nothing happens. 
(As it happens the page believes that my username is undefined)
I have tried this with 3 different emails on 2 different browsers all giving the same result.

My guess is that this has something to do with the controls to the actual game client, as in game m is the button for opening the map and i is the button for the img menu.

I am running Google Chrome v49.0.2623.87 (64-bit), on Mac OS X 10.8.5.

I hope this has been sufficient information for you to address the issue.

If possible, could you fix my main account username as well, making it sync with my glitch username, or at least instruct me on how to correct it. I have tried using the rename button in profile settings but it just spent 1000C on nothing.

Many thanks,

SmiVan.

**Comment by ElleLament** [comment]
@RobertMcDermot :D

**Comment by RobertBlackhart** [comment]
You are pretty observant about the key press errors and the possible reason. That would also be my guess. So good job there.

I would imagine that the reason the "That's totally me" button is greyed out is because the username is already in use and our UI feedback is not working properly.

I think the reason that you see the cupcake is that we cache the image associated with a username. Your was out-of-date/invalid and so you got the default cupcake. I have cleared that cache file and I expect that the next time you log on you should see your appropriate character skin.

Please let me know if this has solved your issue.

**Comment by RobertBlackhart** [comment]
As there hasn't been any response yet, I am going to close this issue. Please feel free to contact us here or at support@childrenofur.com if you have any further problems.
