### ISSUE TITLE
New item should combine with others inside bags if possible

### ISSUE THREAD

**Issue by RobertBlackhart** [ChildrenOfUr/cou-issues#622]
If you have a partial stack of metal rocks (for example) in a bag, getting a new metal rock should place it in that partial stack before putting it in your inventory bar or another bag.

**Comment by RobertBlackhart** [comment]
@klikini,  I see you assigned this to me,  but I already submitted the fix. Did you observe an issue?

**Comment by Klikini** [comment]
Oops, no. I just went through unlabeled/unassigned issues with checkboxes.
