### ISSUE TITLE
Stuck in Flogan Shames

### ISSUE THREAD

**Issue by mutualdesigns** [ChildrenOfUr/cou-issues#63]
No matter what I do, whenever I log in I get a broken Flogan Shames, no avatar, no global chat, no inventory, and I cannot do anything. I've tried on Chrome and Firefox, but nothing seems to work. I've successfully loaded the client before Alpha 1.2.

**Comment by Klikini** [comment]
This is a common issue that happens if you load the game while the server is down (which is often, because the bag features were a bit last-minute).

The server is up now, and we're working on a bug fix release.

Let me know if it doesn't work still.
