### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by sanderstein** [ChildrenOfUr/cou-issues#651]
I died, never went to Hell, and now I cannot access my inventory. I can't buy stuff, I can't nibble the piggies, I can't do anything. Please help! 
![capture](https://cloud.githubusercontent.com/assets/17817807/14222833/f396d18a-f875-11e5-80bd-0dffc6052c7a.PNG)

**Comment by Klikini** [comment]
This is a common issue that we have found and fixed in dev, it will be fixed in the next update. Hang tight :)
