### ISSUE TITLE
Cannot purchase from vendors

### ISSUE THREAD

**Issue by RosieHarper** [ChildrenOfUr/cou-issues#667]
I've got plenty of currents but nowhere to spend them.  Cannot interact with pigs, butterflies, some trees, or cut wood although I own the ax.  Thanks for your help.

Rosie Harper

**Comment by RobertBlackhart** [comment]
This should be fixed by #643

**Comment by RosieHarper** [comment]
None of the issues I listed have been resolved.  I still cannot interact with my bag or the bag IN the bag, nor with most trees, any animals, etc.  
Thanks for your help.Rosie Harper 

```
On Friday, April 8, 2016 4:36 PM, Robert McDermot <notifications@github.com> wrote:
```

 Closed #667.—

**Comment by RobertBlackhart** [comment]
I understand you are not seeing the resolution yet. However, when we are marking issues as fixed, we are doing so because the fixes have been checked into our dev branch. Until we merge with master, you won't see these changes in the live game. Right now our plan for the next release is this coming week and you should see the fix then.

**Comment by RosieHarper** [comment]
Oh!  Thank you for explaining that to me. I apologize for bringing it up again,  Thank you, too, for all the hard work.We truly appreciate having the opportunity to play again.
Blessings,RH 

```
On Thursday, April 14, 2016 5:47 AM, Robert McDermot <notifications@github.com> wrote:
```

 I understand you are not seeing the resolution yet. However, when we are marking issues as fixed, we are doing so because the fixes have been checked into our dev branch. Until we merge with master, you won't see these changes in the live game. Right now our plan for the next release is this coming week and you should see the fix then.—
