### ISSUE TITLE
Scaup Low a bit Over Populated

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#678]
The street is honestly over populated
I mean one can find all the resources available in game in one street, maybe worth a check 
I attach screenshot here
![scaup](https://cloud.githubusercontent.com/assets/6795607/14523316/4befc26c-0233-11e6-8a82-a3215a8cc77f.PNG)

**Comment by RobertBlackhart** [comment]
I have reduced the entities on this street to about what they should be. Thanks for the report, these are helpful.
