### ISSUE TITLE
Different Vendor at Ianara Straight

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#810]
there is a bog vendor alike should be the other kind according to here:
http://www.glitchthegame.com/locations/andra/LA51IOM1PC62SPF/

add screenshot

![ianara](https://cloud.githubusercontent.com/assets/6795607/14951193/6c825418-1057-11e6-8320-31852ad6d2f9.PNG)

**Comment by krisalyssa** [comment]
This appears to be fixed.
