### ISSUE TITLE
Keys not working in game.

### ISSUE THREAD

**Issue by JenPaul1428** [ChildrenOfUr/cou-issues#863]
My name was recently updated from Falafel to Falafel Princess.  Rob helped me out, but now I can't chat in global chat, and some of my keys are not working.  Also, although Falafel Princess appears on the main page as my name, when I am logged in it just says Falafel.

Thank you,

Jen

**Comment by RobertBlackhart** [comment]
Remember,  you need to log out and back in on the client. Hover over the arrow next to the chat panels to see the log out button.
