### ISSUE TITLE
Can't enter game

### ISSUE THREAD

**Issue by KurtWoloch** [ChildrenOfUr/cou-issues#90]
I haven't played Children of Ur for a long time, but wanted to do it today because there is an update about many exciting features. I first tried to log in using Facebook, and I get to the page that says:

Hey, a new face! What do you want to be called?

I entered "Kurt" since "Kurt_Woloch" isn't allowed (too long) and clicked on "That's totally me!" (since there isn't anything else to click on). Now it displays "Loading / Chatting with server..." in the lower left edge and never left that state. Thinking that maybe logging in via Facebook might be broken, I also tried to register with an e-mail address (Kurt_Woloch@hotmail.com), but when trying to start the game I get the same thing. On subsequent visits, it even tries to recognize me, but it says: "Good to see you, Kurt", but then in the next line "Hey, a new face!" and then asks for my name again although it's already given above.

Something's wrong here...

I'm playing the game in Firefox, current version (41.0), on Windows XP.

**Comment by KurtWoloch** [comment]
I've now tried it on Google Chrome, and I'm able to get in there, but the character I should play doesn't appear, so I'm still stuck in the first street I get.

**Comment by Klikini** [comment]
@KurtWoloch Yes, the game sometimes doesn't work in Firefox, though it should work in Chrome. Could you please press F12 in chrome, and post a screenshot of the error console? Thanks, hope I can help with some possible error information :)

**Comment by KurtWoloch** [comment]
Sorry, I couldn't do this. This time I get something that seems to be the "perpetual reload" bug as described in the forum when playing in Chrome, so I don't get to press the F12 key because the game reloads before I get to do anything. However, I tried again in Firefox, and today the game does work in Firefox (after one reload that looked similar to that in Chrome) and it actually runs much more smoothly, but shows quite a few glitches that aren't there in Chrome like garbage sprites on the street and the player showing double pictures. Sorry, that's all I can say right now.

**Comment by Klikini** [comment]
Glad it finally loaded! Not sure why it wasn't before, though.
