### ISSUE TITLE
Error message on the bottom of blog entry

### ISSUE THREAD

**Issue by KurtWoloch** [ChildrenOfUr/cou-issues#91]
On the bottom of the blog page "Alpha 1.2 Update - The Crafting update", there is the following error message between "0 comments" and "Leave a reply":

NULL Warning: Invalid argument supplied for foreach() in /hermes/waloraweb083/b228/moo.childrenofurcom/wordpress/wp-content/themes/coui-wp/functions.php on line 34

**Comment by Klikini** [comment]
Fixed this today (#106)
